In [13]:
# import libraries 
from sklearn.ensemble import GradientBoostingClassifier
import pandas as pd
import numpy as np
from sklearn.preprocessing import StandardScaler
from sklearn.model_selection import train_test_split
#from sklearn.model_selection import GridSearchCV
import matplotlib.pylab as plt
from sklearn.metrics import classification_report
from sklearn.metrics import accuracy_score, confusion_matrix
from sklearn import preprocessing
import warnings
warnings.filterwarnings("ignore")

In [2]:
# define dataset
df = pd.read_csv('PRSA_Data_Aotizhongxin_20130301-20170228.csv' , nrows = 500)

df_new = df.drop(['wd','station'] , axis = 1)
df2 = df_new[np.isfinite(df_new).all(1)]
df2.head()

No  year  month  day  hour  PM2.5  PM10   SO2   NO2     CO    O3  TEMP  \
0   1  2013      3    1     0      4   4.0   4.0   7.0  300.0  77.0  -0.7   
1   2  2013      3    1     1      8   8.0   4.0   7.0  300.0  77.0  -1.1   
2   3  2013      3    1     2      7   7.0   5.0  10.0  300.0  73.0  -1.1   
3   4  2013      3    1     3      6   6.0  11.0  11.0  300.0  72.0  -1.4   
4   5  2013      3    1     4      3   3.0  12.0  12.0  300.0  72.0  -2.0   

     PRES  DEWP  RAIN  WSPM  
0  1023.0 -18.8   0.0   4.4  
1  1023.2 -18.2   0.0   4.7  
2  1023.5 -18.2   0.0   5.6  
3  1024.5 -19.4   0.0   3.1  
4  1025.2 -19.5   0.0   2.0

In [33]:
# Split dataset into test and train data
X_train, X_test, y_train, y_test = train_test_split(df2.drop('CO' , axis = 1) , df2['CO'] , test_size = 0.2)

In [34]:
# define Gradient Boosting Classifier with hyperarameters
gbc = GradientBoostingClassifier(n_estimators = 500 , learning_rate = 0.05 , random_state = 100 , max_features = 5)
# fit train data to gbc
gbc.fit((X_train).round() , ( y_train).round())

GradientBoostingClassifier(ccp_alpha=0.0, criterion='friedman_mse', init=None,
                           learning_rate=0.05, loss='deviance', max_depth=3,
                           max_features=5, max_leaf_nodes=None,
                           min_impurity_decrease=0.0, min_impurity_split=None,
                           min_samples_leaf=1, min_samples_split=2,
                           min_weight_fraction_leaf=0.0, n_estimators=500,
                           n_iter_no_change=None, presort='deprecated',
                           random_state=100, subsample=1.0, tol=0.0001,
                           validation_fraction=0.1, verbose=0,
                           warm_start=False)

In [35]:
prediction = gbc.predict(X_test).round()

In [36]:
from sklearn.metrics import classification_report , confusion_matrix

In [37]:
from sklearn.metrics import accuracy_score
accuracy_score((y_test).round() , prediction)

0.24742268041237114

In [38]:
# Confusion matrix will give number of correct and incorrect classifications
print(confusion_matrix((y_test).round() , prediction))

[[3 0 0 ... 0 0 0]
 [0 7 0 ... 0 0 0]
 [0 2 3 ... 0 0 0]
 ...
 [0 0 0 ... 0 0 0]
 [0 0 0 ... 0 0 0]
 [0 0 0 ... 0 0 0]]


In [39]:
# check the classification report
print(classification_report((y_test).round() , prediction))

              precision    recall  f1-score   support

       300.0       1.00      1.00      1.00         3
       400.0       0.78      1.00      0.88         7
       500.0       0.33      0.38      0.35         8
       600.0       0.00      0.00      0.00         5
       700.0       0.62      0.56      0.59         9
       800.0       0.00      0.00      0.00         2
       900.0       0.50      0.50      0.50         2
      1000.0       0.00      0.00      0.00         0
      1100.0       0.17      0.25      0.20         4
      1200.0       0.00      0.00      0.00         2
      1300.0       0.00      0.00      0.00         1
      1399.0       0.00      0.00      0.00         2
      1500.0       0.00      0.00      0.00         3
      1600.0       0.17      0.17      0.17         6
      1700.0       1.00      0.14      0.25         7
      1800.0       0.00      0.00      0.00         1
      1899.0       0.00      0.00      0.00         3
      2000.0       0.00    

In [40]:
# find the accuracy of model
print("GBC accuracy is %2.2f" % accuracy_score( 
     (y_test).round(), gbc.predict(X_test)))

GBC accuracy is 0.25
